CREATE DATABASE STORYTELLER
	DEFAULT CHARACTER SET UTF8MB4
    DEFAULT COLLATE UTF8MB4_0900_AI_CI;
    
USE STORYTELLER;

-- USERS TABLE
CREATE TABLE USERS(
	USER_ID 		    INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL			    VARCHAR(255) NOT NULL UNIQUE, 
    FIRST_NAME    VARCHAR(100) NOT NULL,
    LAST_NAME     VARCHAR(100) NOT NULL,
    ROLE			    ENUM('AUTHOR','EDITOR','ADMIN') DEFAULT 'AUTHOR',
    PASSWORD 		  VARCHAR(255) NOT NULL,
    CREATED_AT 		TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB;

-- STORIES TABLE
CREATE TABLE STORIES(
    STORY_ID 		  SMALLINT(6) AUTO_INCREMENT PRIMARY KEY,
    USER_ID 		  SMALLINT(6) NOT NULL,
    TITLE 		  	VARCHAR(200) NOT NULL,
    SYNOPSIS   		TEXT, 
    GENRE    			VARCHAR(100),
	  CREATED_AT 		TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT 		TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_STORIES_USER
		FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
        ON DELETE CASCADE
	) ENGINE=INNODB;

CREATE INDEX IDX_STORIES_USER ON STORIES(USER_ID); -- INDEX OF STORIES USING USER_ID AS REFERENCE

-- CHARACTERS TABLE
CREATE TABLE CHARACTERS(
	CHARACTER_ID 	  INT(11) AUTO_INCREMENT PRIMARY KEY,
    STORY_ID		  SMALLINT(6) NOT NULL,
    NAME			    VARCHAR(150) NOT NULL,
    AGE 			    VARCHAR(50),
    DESCRIPTION   TEXT,
    NOTES  			  TEXT,
    CREATED_AT 		TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT 		TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_CHARACTERS_STORY
		FOREIGN KEY (STORY_ID) REFERENCES STORIES(STORY_ID),
        ON DELETE CASCADE
        ON UPDATE CASCADE
	) ENGINE=INNODB;
    
CREATE INDEX IDX_CHARACTERS_STORY ON CHARACTERS(STORY_ID); -- CREATE CHARACTERS INDEX

-- LOCATION TABLE
CREATE TABLE LOCATIONS(
	LOCATION_ID 	  INT(11) AUTO_INCREMENT PRIMARY KEY,
    STORY_ID		  SMALLINT(6) NOT NULL,
    NAME		    	VARCHAR(150) NOT NULL,
    DESCRIPTION		TEXT,
    CREATED_AT 		TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT 		TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_LOCATIONS_STORY
		FOREIGN KEY(STORY_ID) REFERENCES STORIES(STORY_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE=INNODB;

CREATE INDEX IDX_LOCATIONS_STORY ON LOCATIONS(STORY_ID); -- CREATE LOCATAIONS INDEX

-- PLOT POINTS TABLE
CREATE TABLE PLOT_POINTS(
	PLOT_POINT_ID	  INT(11) AUTO_INCREMENT PRIMARY KEY,
    STORY_ID		  SMALLINT(6) NOT NULL,
    TITLE 			  VARCHAR(200) NOT NULL,
    SUMMARY			  TEXT, 
    SEQUENCE_NO 	INT NULL,	-- FOR SEQUENTIAL TIMELINE
    LOCATION_ID 	INT NULL,
    CREATED_AT 		TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT 		TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_PLOTPOINTS_STORY
		FOREIGN KEY (STORY_ID) REFERENCES STORIES(STORY_ID)
        ON DELETE CASCADE,
	CONSTRAINT FK_PLOTPOINTS_LOCATION
		FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID)
        ON DELETE SET NULL
) ENGINE=INNODB;

CREATE INDEX IDX_PLOTPOINTS_STORY ON PLOT_POINTS(STORY_ID); -- CREATE INDEX OF PLOT POINTS
CREATE INDEX IDX_PLOTPOINTS_ORDER ON PLOT_POINTS(STORY_ID, SEQUENCE_NO); -- CREATE ORDERED INDEX OF PLOT POINTS FOR CALENDAR TIMELINE

CREATE TABLE plot_point_characters (
    PLOT_POINT_ID  INT NOT NULL,
    CHARACTER_ID   INT NOT NULL,

    -- Prevent duplicates
    PRIMARY KEY (plot_point_id, character_id),

    -- Ensure valid references
    FOREIGN KEY (plot_point_id)
        REFERENCES plot_points(plot_point_id)
        ON DELETE CASCADE,

    FOREIGN KEY (character_id)
        REFERENCES characters(character_id)
        ON DELETE CASCADE
)ENGINE=INNODB;
    
CREATE INDEX IDX_PLOTPOINTS_CHARACTERS ON PLOT_POINTS(CHARACTER_ID); -- CREATE INDEX OF PLOT POINTS BY CHARACTER
    
    
    
    
    
    
    
    
    
    
    