/*  Storyteller Database Last Activity Triggers
    --------------------------------------
    This SQL script creates triggers to update the LAST_ACTIVITY timestamp
    in the STORIES table whenever there are INSERT, UPDATE, or DELETE operations
    on the CHARACTERS, LOCATIONS, TIMELINE, and TIMELINE_CHARACTERS tables.
    This helps in tracking the most recent activity related to each story.
    --------------------------------------
    Updated; November 2025
    Changes:
    1. Created triggers for CHARACTERS, LOCATIONS, TIMELINE, and TIMELINE_CHARACTERS tables.
*/
-- LAST_ACTIVITY TRIGGERS FOR CHARACTERS
-- After INSERT on CHARACTERS
CREATE TRIGGER TRG_CHARACTERS_AI
AFTER INSERT ON CHARACTERS
FOR EACH ROW
  UPDATE STORIES
  SET LAST_ACTIVITY = NOW()
  WHERE STORY_ID = NEW.STORY_ID;


-- After UPDATE on CHARACTERS
CREATE TRIGGER TRG_CHARACTERS_AU
AFTER UPDATE ON CHARACTERS
FOR EACH ROW
  UPDATE STORIES
  SET LAST_ACTIVITY = NOW()
  WHERE STORY_ID = NEW.STORY_ID;
-- After DELETE on CHARACTERS
CREATE TRIGGER TRG_CHARACTERS_AD
AFTER DELETE ON CHARACTERS
FOR EACH ROW
  UPDATE STORIES
  SET LAST_ACTIVITY = NOW()
  WHERE STORY_ID = OLD.STORY_ID;
-- LAST_ACTIVITY TRIGGERS FOR LOCATIONS
-- After INSERT on LOCATIONS
CREATE TRIGGER TRG_LOCATIONS_AI
AFTER INSERT ON LOCATIONS
FOR EACH ROW
  UPDATE STORIES
  SET LAST_ACTIVITY = NOW()
  WHERE STORY_ID = NEW.STORY_ID;


-- After UPDATE on LOCATIONS
CREATE TRIGGER TRG_LOCATIONS_AU
AFTER UPDATE ON LOCATIONS
FOR EACH ROW
  UPDATE STORIES
  SET LAST_ACTIVITY = NOW()
  WHERE STORY_ID = NEW.STORY_ID;

-- After DELETE on LOCATIONS
CREATE TRIGGER TRG_LOCATIONS_AD
AFTER DELETE ON LOCATIONS
FOR EACH ROW
  UPDATE STORIES
  SET LAST_ACTIVITY = NOW()
  WHERE STORY_ID = OLD.STORY_ID;

-- LAST_ACTIVITY TRIGGERS FOR TIMELINE
-- After INSERT on TIMELINE
CREATE TRIGGER TRG_TIMELINE_AI
AFTER INSERT ON TIMELINE
FOR EACH ROW
  UPDATE STORIES
  SET LAST_ACTIVITY = NOW()
  WHERE STORY_ID = NEW.STORY_ID;

-- After UPDATE on TIMELINE
CREATE TRIGGER TRG_TIMELINE_AU
AFTER UPDATE ON TIMELINE
FOR EACH ROW
  UPDATE STORIES
  SET LAST_ACTIVITY = NOW()
  WHERE STORY_ID = NEW.STORY_ID;

-- After DELETE on TIMELINE
CREATE TRIGGER TRG_TIMELINE_AD
AFTER DELETE ON TIMELINE
FOR EACH ROW
  UPDATE STORIES
  SET LAST_ACTIVITY = NOW()
  WHERE STORY_ID = OLD.STORY_ID;
   
-- LAST_ACTIVITY TRIGGERS FOR TIMELINE_CHARACTERS
-- After INSERT on TIMELINE_CHARACTERS
CREATE TRIGGER TRG_TIMELINE_CHARACTERS_AI
AFTER INSERT ON TIMELINE_CHARACTERS
FOR EACH ROW
  UPDATE STORIES
  SET LAST_ACTIVITY = NOW()
  WHERE STORY_ID = NEW.STORY_ID;


-- After UPDATE on TIMELINE_CHARACTERS
CREATE TRIGGER TRG_TIMELINE_CHARACTERS_AU
AFTER UPDATE ON TIMELINE_CHARACTERS
FOR EACH ROW
  UPDATE STORIES
  SET LAST_ACTIVITY = NOW()
  WHERE STORY_ID = NEW.STORY_ID;


-- After DELETE on TIMELINE_CHARACTERS
CREATE TRIGGER TRG_TIMELINE_CHARACTERS_AD
AFTER DELETE ON TIMELINE_CHARACTERS
FOR EACH ROW
  UPDATE STORIES
  SET LAST_ACTIVITY = NOW()
  WHERE STORY_ID = OLD.STORY_ID;
